"""
TaskFlow Pro - Task Management SaaS Application
Generated by BhogarAI Greenfield Workflow Pipeline
Deployed to Azure App Service via Service Principal Authentication
"""
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime, timezone
from enum import Enum
import uuid
import os

app = FastAPI(
    title="TaskFlow Pro",
    description="Collaborative Task Management SaaS - Built by BhogarAI Greenfield Pipeline",
    version="1.0.0",
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Models ────────────────────────────────────────────────────

class Priority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class TaskStatus(str, Enum):
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "review"
    DONE = "done"

class TaskCreate(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    description: Optional[str] = None
    priority: Priority = Priority.MEDIUM
    status: TaskStatus = TaskStatus.TODO
    assignee: Optional[str] = None
    sprint: Optional[str] = None
    tags: List[str] = []

class Task(TaskCreate):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

class BoardColumn(BaseModel):
    id: str
    name: str
    tasks: List[Task] = []

class Board(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    columns: List[BoardColumn] = []

class Sprint(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    start_date: str
    end_date: str
    tasks: List[str] = []  # task IDs

class TeamMember(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    email: str
    role: str = "member"  # admin, manager, member, viewer


# ── In-Memory Storage ────────────────────────────────────────

tasks_db: dict[str, Task] = {}
boards_db: dict[str, Board] = {}
sprints_db: dict[str, Sprint] = {}
team_db: dict[str, TeamMember] = {}

# Seed demo data
def seed_demo_data():
    # Team members
    members = [
        TeamMember(name="Alice Chen", email="alice@taskflow.pro", role="admin"),
        TeamMember(name="Bob Martinez", email="bob@taskflow.pro", role="manager"),
        TeamMember(name="Carol Smith", email="carol@taskflow.pro", role="member"),
        TeamMember(name="Dave Johnson", email="dave@taskflow.pro", role="member"),
    ]
    for m in members:
        team_db[m.id] = m

    # Tasks
    demo_tasks = [
        Task(title="Set up CI/CD pipeline", description="Configure GitHub Actions for automated deployments", priority=Priority.HIGH, status=TaskStatus.DONE, assignee="Alice Chen", tags=["devops", "infrastructure"]),
        Task(title="Design database schema", description="Create PostgreSQL schema for tasks, boards, sprints", priority=Priority.HIGH, status=TaskStatus.DONE, assignee="Bob Martinez", tags=["backend", "database"]),
        Task(title="Implement REST API", description="Build FastAPI endpoints for CRUD operations", priority=Priority.HIGH, status=TaskStatus.IN_PROGRESS, assignee="Carol Smith", tags=["backend", "api"]),
        Task(title="Build Kanban board UI", description="React drag-and-drop Kanban board component", priority=Priority.MEDIUM, status=TaskStatus.IN_PROGRESS, assignee="Dave Johnson", tags=["frontend", "ui"]),
        Task(title="Add real-time collaboration", description="WebSocket-based live updates across team", priority=Priority.MEDIUM, status=TaskStatus.TODO, assignee="Alice Chen", tags=["backend", "realtime"]),
        Task(title="Implement RBAC", description="Role-based access control: Admin, Manager, Member, Viewer", priority=Priority.HIGH, status=TaskStatus.TODO, tags=["security", "auth"]),
        Task(title="Slack integration", description="Webhook notifications to Slack channels", priority=Priority.LOW, status=TaskStatus.TODO, tags=["integration"]),
        Task(title="Time tracking feature", description="Log hours per task with reporting", priority=Priority.MEDIUM, status=TaskStatus.TODO, assignee="Bob Martinez", tags=["feature"]),
        Task(title="Gantt chart view", description="Timeline visualization for sprint planning", priority=Priority.LOW, status=TaskStatus.TODO, tags=["frontend", "visualization"]),
        Task(title="SOC2 compliance audit", description="Prepare audit logging and data encryption", priority=Priority.CRITICAL, status=TaskStatus.IN_REVIEW, assignee="Alice Chen", tags=["security", "compliance"]),
    ]
    for t in demo_tasks:
        tasks_db[t.id] = t

    # Board
    board = Board(
        name="TaskFlow Pro - Sprint 1",
        columns=[
            BoardColumn(id="col-todo", name="To Do", tasks=[t for t in demo_tasks if t.status == TaskStatus.TODO]),
            BoardColumn(id="col-progress", name="In Progress", tasks=[t for t in demo_tasks if t.status == TaskStatus.IN_PROGRESS]),
            BoardColumn(id="col-review", name="In Review", tasks=[t for t in demo_tasks if t.status == TaskStatus.IN_REVIEW]),
            BoardColumn(id="col-done", name="Done", tasks=[t for t in demo_tasks if t.status == TaskStatus.DONE]),
        ]
    )
    boards_db[board.id] = board

    # Sprint
    sprint = Sprint(
        name="Sprint 1 - MVP Foundation",
        start_date="2026-04-01",
        end_date="2026-04-14",
        tasks=[t.id for t in demo_tasks[:6]]
    )
    sprints_db[sprint.id] = sprint

seed_demo_data()


# ── API Endpoints ─────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def home():
    """TaskFlow Pro Dashboard"""
    task_list = list(tasks_db.values())
    todo = [t for t in task_list if t.status == TaskStatus.TODO]
    in_progress = [t for t in task_list if t.status == TaskStatus.IN_PROGRESS]
    in_review = [t for t in task_list if t.status == TaskStatus.IN_REVIEW]
    done = [t for t in task_list if t.status == TaskStatus.DONE]
    
    def task_card(task):
        priority_colors = {"low": "#10b981", "medium": "#f59e0b", "high": "#ef4444", "critical": "#dc2626"}
        priority_bg = {"low": "#d1fae5", "medium": "#fef3c7", "high": "#fee2e2", "critical": "#fecaca"}
        tags_html = "".join(f'<span class="tag">{tag}</span>' for tag in task.tags)
        assignee_html = f'<div class="assignee">👤 {task.assignee}</div>' if task.assignee else ''
        return f"""
        <div class="task-card" draggable="true" data-id="{task.id}">
            <div class="task-header">
                <span class="priority" style="background:{priority_bg.get(task.priority.value, '#e5e7eb')};color:{priority_colors.get(task.priority.value, '#6b7280')}">{task.priority.value.upper()}</span>
            </div>
            <h4>{task.title}</h4>
            <p class="desc">{task.description or ''}</p>
            <div class="tags">{tags_html}</div>
            {assignee_html}
        </div>"""

    def column_html(title, tasks, col_id):
        cards = "".join(task_card(t) for t in tasks)
        return f"""
        <div class="column" id="{col_id}">
            <div class="column-header">
                <h3>{title}</h3>
                <span class="count">{len(tasks)}</span>
            </div>
            <div class="cards">{cards}</div>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskFlow Pro - Task Management</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f0f2f5; color: #1a1a2e; }}
        .navbar {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 16px 32px; display: flex; align-items: center; justify-content: space-between; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .navbar h1 {{ font-size: 24px; display: flex; align-items: center; gap: 10px; }}
        .navbar .subtitle {{ opacity: 0.8; font-size: 14px; }}
        .stats {{ display: flex; gap: 20px; padding: 20px 32px; }}
        .stat-card {{ background: white; border-radius: 12px; padding: 20px 24px; flex: 1; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .stat-card .value {{ font-size: 32px; font-weight: 700; color: #667eea; }}
        .stat-card .label {{ color: #6b7280; font-size: 14px; margin-top: 4px; }}
        .board {{ display: flex; gap: 16px; padding: 0 32px 32px; overflow-x: auto; }}
        .column {{ background: #e5e7eb; border-radius: 12px; min-width: 300px; flex: 1; padding: 16px; }}
        .column-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; padding: 0 4px; }}
        .column-header h3 {{ font-size: 16px; color: #374151; }}
        .count {{ background: #9ca3af; color: white; border-radius: 50%; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 600; }}
        .cards {{ display: flex; flex-direction: column; gap: 10px; min-height: 50px; }}
        .task-card {{ background: white; border-radius: 8px; padding: 14px; box-shadow: 0 1px 2px rgba(0,0,0,0.06); cursor: grab; transition: transform 0.15s, box-shadow 0.15s; border-left: 3px solid transparent; }}
        .task-card:hover {{ transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
        .task-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }}
        .priority {{ padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; }}
        .task-card h4 {{ font-size: 14px; margin-bottom: 6px; color: #1f2937; }}
        .desc {{ font-size: 12px; color: #6b7280; margin-bottom: 8px; line-height: 1.4; }}
        .tags {{ display: flex; gap: 4px; flex-wrap: wrap; margin-bottom: 6px; }}
        .tag {{ background: #ede9fe; color: #7c3aed; padding: 2px 8px; border-radius: 4px; font-size: 11px; }}
        .assignee {{ font-size: 12px; color: #4b5563; }}
        .footer {{ text-align: center; padding: 20px; color: #9ca3af; font-size: 13px; }}
        .deploy-badge {{ background: rgba(255,255,255,0.2); padding: 6px 14px; border-radius: 20px; font-size: 12px; }}
        .team {{ padding: 20px 32px; }}
        .team h2 {{ margin-bottom: 12px; color: #374151; }}
        .team-grid {{ display: flex; gap: 12px; flex-wrap: wrap; }}
        .member {{ background: white; border-radius: 8px; padding: 14px 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); min-width: 200px; }}
        .member .name {{ font-weight: 600; color: #1f2937; }}
        .member .email {{ font-size: 12px; color: #6b7280; }}
        .member .role {{ display: inline-block; margin-top: 6px; padding: 2px 8px; border-radius: 4px; font-size: 11px; background: #dbeafe; color: #1d4ed8; }}
    </style>
</head>
<body>
    <nav class="navbar">
        <div>
            <h1>📋 TaskFlow Pro</h1>
            <div class="subtitle">Collaborative Task Management for Teams</div>
        </div>
        <div class="deploy-badge">🚀 Deployed on Azure App Service | Built by BhogarAI</div>
    </nav>
    
    <div class="stats">
        <div class="stat-card"><div class="value">{len(task_list)}</div><div class="label">Total Tasks</div></div>
        <div class="stat-card"><div class="value">{len(todo)}</div><div class="label">To Do</div></div>
        <div class="stat-card"><div class="value">{len(in_progress)}</div><div class="label">In Progress</div></div>
        <div class="stat-card"><div class="value">{len(done)}</div><div class="label">Completed</div></div>
    </div>
    
    <div class="board">
        {column_html("📝 To Do", todo, "todo")}
        {column_html("🔄 In Progress", in_progress, "in-progress")}
        {column_html("👀 In Review", in_review, "review")}
        {column_html("✅ Done", done, "done")}
    </div>
    
    <div class="team">
        <h2>👥 Team Members</h2>
        <div class="team-grid">
            {"".join(f'<div class="member"><div class="name">{m.name}</div><div class="email">{m.email}</div><div class="role">{m.role}</div></div>' for m in team_db.values())}
        </div>
    </div>
    
    <div class="footer">
        TaskFlow Pro v1.0.0 | Generated by BhogarAI Greenfield Workflow | Deployed via Azure Service Principal | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
    </div>
</body>
</html>"""


# ── REST API ──────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {
        "status": "healthy",
        "app": "TaskFlow Pro",
        "version": "1.0.0",
        "deployed_on": "Azure App Service",
        "deployed_by": "BhogarAI Greenfield Workflow",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "tasks_count": len(tasks_db),
        "team_count": len(team_db),
    }

@app.get("/api/tasks", response_model=List[Task])
async def list_tasks(status: Optional[str] = None, priority: Optional[str] = None):
    tasks = list(tasks_db.values())
    if status:
        tasks = [t for t in tasks if t.status.value == status]
    if priority:
        tasks = [t for t in tasks if t.priority.value == priority]
    return tasks

@app.post("/api/tasks", response_model=Task, status_code=201)
async def create_task(task: TaskCreate):
    new_task = Task(**task.model_dump())
    tasks_db[new_task.id] = new_task
    return new_task

@app.get("/api/tasks/{task_id}", response_model=Task)
async def get_task(task_id: str):
    if task_id not in tasks_db:
        raise HTTPException(status_code=404, detail="Task not found")
    return tasks_db[task_id]

@app.put("/api/tasks/{task_id}", response_model=Task)
async def update_task(task_id: str, task: TaskCreate):
    if task_id not in tasks_db:
        raise HTTPException(status_code=404, detail="Task not found")
    updated = Task(**task.model_dump(), id=task_id, updated_at=datetime.now(timezone.utc).isoformat())
    tasks_db[task_id] = updated
    return updated

@app.delete("/api/tasks/{task_id}")
async def delete_task(task_id: str):
    if task_id not in tasks_db:
        raise HTTPException(status_code=404, detail="Task not found")
    del tasks_db[task_id]
    return {"message": "Task deleted"}

@app.get("/api/boards", response_model=List[Board])
async def list_boards():
    return list(boards_db.values())

@app.get("/api/sprints", response_model=List[Sprint])
async def list_sprints():
    return list(sprints_db.values())

@app.get("/api/team", response_model=List[TeamMember])
async def list_team():
    return list(team_db.values())

@app.get("/api/stats")
async def get_stats():
    tasks = list(tasks_db.values())
    return {
        "total_tasks": len(tasks),
        "by_status": {s.value: len([t for t in tasks if t.status == s]) for s in TaskStatus},
        "by_priority": {p.value: len([t for t in tasks if t.priority == p]) for p in Priority},
        "team_size": len(team_db),
        "sprints": len(sprints_db),
        "boards": len(boards_db),
    }
